export const airports: string[] = [
  "Hartsfield–Jackson Atlanta International Airport",
  "Dallas Fort Worth International Airport",
  "Denver International Airport",
  "O'Hare International Airport",
  "Los Angeles International Airport",
  "Charlotte Douglas International Airport",
  "Orlando International Airport",
  "Guangzhou Baiyun International Airport",
  "Chengdu Shuangliu International Airport",
  "Harry Reid International Airport",
  "Phoenix Sky Harbor International Airport",
  "Miami International Airport",
  "Indira Gandhi International Airport",
  "Istanbul Airport",
  "Shenzhen Bao'an International Airport",
  "Seattle–Tacoma International Airport",
  "Mexico City International Airport",
  "Chongqing Jiangbei International Airport",
  "Shanghai Hongqiao International Airport",
  "Beijing Capital International Airport",
  "Kunming Changshui International Airport",
  "Shanghai Pudong International Airport",
  "George Bush Intercontinental Airport",
  "Sheremetyevo International Airport",
  "John F. Kennedy International Airport",
  "Xi'an Xianyang International Airport",
  "Dubai International Airport",
  "Newark Liberty International Airport",
  "Hangzhou Xiaoshan International Airport",
  "Fort Lauderdale–Hollywood International Airport",
  "Charles de Gaulle Airport",
  "Tokyo Haneda Airport",
  "Jeju International Airport",
  "Amsterdam Airport Schiphol",
  "Moscow Domodedovo Airport",
  "Beijing Daxing International Airport",
  "Istanbul Sabiha Gökçen International Airport",
  "Frankfurt Airport",
  "Minneapolis/St Paul International Airport",
  "San Francisco International Airport",
  "São Paulo/Guarulhos International Airport",
  "Adolfo Suárez Madrid–Barajas Airport",
  "Detroit Metropolitan Airport",
  "Logan International Airport",
  "Gimpo International Airport",
  "Cancún International Airport",
  "Salt Lake City International Airport",
  "Antalya Airport",
  "Changsha Huanghua International Airport",
  "Wuhan Tianhe International Airport",
];
